#+title: To-Do List Of Most Important Things
#+author: AAkselrod

* 2022-06-07
** DONE Запланировать новый спринт в PP
CLOSED: [2022-06-07 Tue 15:04]
** DONE Улететь в Спб
CLOSED: [2022-06-08 Wed 10:31]
- Вылет 18-05
- Окончание регистрации 17-20
- Прибытие в аэропорт 16-50
- Поездка на такси 44 минуты, с запасом 1 час
- Выход из офиса 15-50
** DONE Провести 1-1 с Колей
CLOSED: [2022-06-08 Wed 11:29]
*** Загрузка на S5-S6
*** Контроль качества в команде
**** Обратная связь про Руслана: что полезного делает
**** Аудит качества со стороны юнита QA
*** Планирование квартала
**** Что будет делать команда в Q2
**** Какая ввродная от команды продакта?
*** Большое количество встреч у Дениса
*** Обзор прошедшего спринта
**** Что выпустили
**** Что хотели выпустить и не выпустили. Анализ причин
**** Что делаем в следующий раз, чтобы выпустить
**** Прогресс по роадмапу
**** Метрики спринта - скоп-дроп (что-то еще?)
**** Замечания по результатам ретроспективы
*** Обзор текущего спринта
**** Содержание - что запланировали на очередной спринт - согласованность с роадмапом/ожидаемой ценностью для продукта
**** Утилизация участников команды - равномерность загрузки
**** Как учтены выводы с прошлого спринта в планировании/выполнении текущего
*** Тех проекты
**** Прогресс по тех проектам
**** План до следующего Op-Review
*** Люди
**** Мотивация/трудности/заметные достижения
**** Обзор продвижения по ИПРам
** DONE Подумать про процесс качества
CLOSED: [2022-06-08 Wed 10:32]
Проблематика: в проде на IMV лендинге оказался срок экспозиции равный 1 день. Дефект проскочил в прод, по обращениям пользователя мы это понять не смогли (видимо
никто про это не думал сообщать. Хотелось бы подумать про продвинутую работу мониторинга для выявления подобных дефектов.
*** Обсудить проблематику с юнитом QA в лице Трусовой
По результатам обсуждения: такой практики живой нет, по результатам обнаружения дефектов настраиваем мониторинг и пишем дополнительные автотесты.
** DONE Провести представление архитектуры для Леши И
CLOSED: [2022-06-07 Tue 14:46]
** DONE Подумать про формирование общей ответственности за ОКРы у лидов и продактов
CLOSED: [2022-06-08 Wed 11:29]
Сейчас тим лиды осознают свою ответственность только за цели деливери. Также некоторые цели дискавери заключаются в контроле внешних команд разработки (горизонталей,
внешних подрядчиков). В контроле/проектировании этих задач ценной является техническая экспертиза.

Если расширить фокус тим лидов с команды деливери на цели команды в общем, то качество работы команды с т з бизнеса повысится.

*** с Пашей обсудить, как такая ерунда возникла


*** dsds

1. dsdsd
   dsadasdsadas
2. dsdsdsd
3. dsdsdsdsd
   dsdsd
   sdsd
4. dsdsd
5. dsdsd
   dsdsdsd
   - [ ] TODO dsdsds
     - 
      

* <2022-06-08 Wed>
** DONE Отчитаться по командировке
CLOSED: [2022-06-08 Wed 15:50]
Скан-копии документов отправляете на почту adv.reports@avito.ru, а оригиналы предоставляете в Бухгалтерию в городе Москва (Лесная, 7,  тут) или сотрудникам административной поддержки в городе Санкт-Петербург.

Более подробную информацию об отчетности по командировке можно найти в [[https://cf.avito.ru/pages/viewpage.action?pageId=87278067][CF Как отчитаться за командировку.]] 

Если у вас возникают вопросы по отчетности за командировку, пишите на электронный адрес - adv.reports@avito.ru, а также в slack - #adv_reports, ответственные сотрудники помогут вам.
** DONE Оформить результаты ретро РР
CLOSED: [2022-06-08 Wed 15:44]
1. Формат нового дейли со сменным ведущим зашел
2. При планировании очередного спринта учитываем DoD - код написан, код ревью пройдено, задача протестирована, интеграционные тесты написаны, баги исправлены
3. Ведущему дейлика на заметку - обсуждения нужно модерировать и укладываться в 15 минут. Например через установку тайминга. Если не укладываешься, то заинтересованные участники уходят в оффлайн
4. Начинаем катиться в прод во вторник (выкатываем все, что есть), заканчиваем в среду
5. Разработку реализуем через транк-бейзд девелопмент. Переход завершаем в начале FY’22 Q2
   - Пререквизит 1 - добиться достойного покрытия тестами
   - Пререквизит 2 - разработать адекватный мониторинг
6. Описать про транк-бейзд в конфлу
7. Разработать автотесты для проверки участия ОН в ПП в рамках S5
8. Разработку таска FE+BE начинаем с разработки сваггер-схемы. При этом сваггер схему может делать как фронт, так и бек
9. Тестирование фронта осуществляем на sample-приложении
10. К внутреннему демо нужно готовиться
11. Если при реализации задачи чего-то делать не нужно (что может быть указано в дизайне), то явно об этом писать.
12. По результатам изменения таски модифицировать ее описание и сигнализировать об этом в командный чат
13. По результатам реализации, если есть какие-то нетривиальные/неявные изменения, которые нужно протестить, то писать об этом явно (чтобы это работало сделать чек-лист DoD). Также если реализация отличается от того, что есть в описании таска, то нужно об это явно написать. И писать о факте изменения в командном чате.
14. Основаная сущность - юзер стори. Задачи на бек/фронт/сваггера апи и пр - это сабтаски в юзер сторе. Таски - это тех долг. Импрувменты не используем. Если будет не удобно, то пересматриваем в сторону итеративного подхода - сперва бек, потом фронт.
15. В Спб пробуем обсудить про тактику тестирования - когда какие тесты в каком объеме нужно писать.
    - Вадим рассказывает про флоу создания интеграционных тестов
    - Составляем список имеющихся трудностей
    - Генерим решения
16. На внутреннем демо определяемся, что мы будем показывать на Спринт Ревью

** TODO Описать в конфлу PP про Trunk Based Development


| name  | surname                |
|-------+------------------------|
| Саша  | Аксельрод              |
| Элина | Владимировна Аксельрод |
|       |                        |

| adadasd | fsdfsfsdfd            |
|---------+-----------------------|
| Sasha   | Akselrod              |
| Elina   | Vladimirovna Akselrod |
|         |                       |




| Имя       | Фамилия                |
|-----------+------------------------|
| Александр | Аксельрод              |
| Элина     | Владимировна Аксельрод |
|           |                        |


| Имя       | Фамилия   |
|-----------+-----------|
| Александр | Аксельрод |
|           |           |
