#+ Op-Review Паша
* <2022-06-08 Wed>
** Обзор прошедшего спринта
- *Что выпустили*
  Android ВГ Сервисы
- *Что хотели выпустить и не выпустили. Анализ причин*
  Долгое Code Review с горизонталями - планировки. Долго - , целевая - , для тяжелых пулл реков могут долго реагировать. 
  Точность определения планировок с DS-SWAT - планировки
  Front ВГ Сервисы - могли бы выпустить, почему-то не выпустили
  Все фильтры - непонятная арх-ра, нужно думать 
- *Что делаем в следующий раз, чтобы выпустить*
  Делаем буферы - все время спринта не занимаем
- *Прогресс по роадмапу*
  Все фильтры - ждем пятницу, чтобы финализировать решение
  Планировки - завершаем квартал на А-Б
  ВГлавная - не успеваем затащить все промо-блоки, по фронту On-Track
- *Метрики спринта - скоп-дроп (что-то еще?)*
  55%
- *Замечания по результатам ретроспективы*
  Мобильная разработка занимается STR'ом (приходится заниматься саппортом/багфиксом/иногда на той команде меняют АПИ - нужно поддерживать)
  Нужны DoR'ы/DoD'ы для задач по ресерчу
  
** Обзор текущего спринта
- *Содержание - что запланировали на очередной спринт - согласованность с роадмапом/ожидаемой ценностью для продукта*
  Планировки и планирование
- *Утилизация участников команды - равномерность загрузки*
  Фронты равномерно, в беке есть пустоты под планирование и Все фильтры под Влада.
- *Тех проекты*
  Договариваемся о добавлении "domofond в рамках проекта k-ветки и ИМ" в Whitelist
- *План до следующего Op-Review*
  - [ ] разработать план того, как нам уменьшить Скоп Дроп <2022-06-14 Tue>
  - [ ] разобраться с тем, как работает [[https://bi.avito.ru/#/views/AgileDashboard/AgileDashboard/6468f6fa-50f2-40ef-8d5a-8dfb9c4060b2/3d6e5528-f34e-4a75-9a7d-e42a4bdafdf9?:display_count=n&:iid=1&:origin=viz_share_link&:showVizHome=n][dashboard]]  
** Люди
- *Мотивация/трудности/заметные достижения*
  - Тимуру дали контрольную задачу, по результатам принимаем решение - сливать/не сливать
  - Влад активизировался
- *Обзор продвижения по ИПРам*
  - Егора отправить на E6
  - Илья К отправить на E5

* Неразобранное
** TODO проработать SLA реакции и завершения Code Review
** TODO проверить текущий дизайн команды на адекватность стоящим перед командой целям
** TODO подумать, с кем можно валидировать план прокачки на E6 - насколько этого достаточно для E6
** TODO продумать, что делаем с мобильными разработчиками


